Try to find gcov

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,12 +1,12 @@
 name: Run build
 on:
-  pull_request:
-    types: [opened, synchronize, reopened]
+#  pull_request:
+#    types: [opened, synchronize, reopened]
   push:
     branches:
-      - main
-  schedule:
-    - cron: "0 7 * * 1,3,5"
+      - collect_coverage
+#  schedule:
+#    - cron: "0 7 * * 1,3,5"
 env:
   VBUILD_UNIT_TESTS: true
   CONAN_VER: 1.57.0
@@ -86,7 +86,7 @@ jobs:
       - name: Run build-wrapper
         run: |
           # remove folder with copied gcov files to avoid unnecessary growth of Duplicated Code
-          rm -rf /home/runner/work/client-cpp/client-cpp/src/folder_with_gcov_files
+#          rm -rf /home/runner/work/client-cpp/client-cpp/src/folder_with_gcov_files
           cd ${{ github.workspace }}
           cd src
           build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR_SONAR }} ./build-all.sh
@@ -119,112 +119,112 @@ jobs:
             code-coverage.tar.gz
       - run: echo "🍏 This job's status is ${{ job.status }}."
 
-  run-build-windows:
-    runs-on: windows-2019
-    needs: run-build-ubuntu
-    env:
-      VBUILDRELEASE: Release
-      VBUILDDEBUG: Debug
-      VBUILDMODE: Release
-    steps:
-      - run: echo "🎉 The job was automatically triggered by a %github.event_name% event."
-      - run: echo "🐧 This job is now running on a %runner.os% server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is %github.ref% and your repository is %github.repository%."
-
-      - name: Check out repository code
-        uses: actions/checkout@v3
-      - run: echo "💡 The %github.repository% repository has been cloned to the runner."
-
-      - name: Install Conan
-        run: pip3 install conan==${{ env.CONAN_VER }} --force
-
-      - name: Setup MSBuild
-        uses: microsoft/setup-msbuild@v1
-
-      - name: Run build
-        run: |
-          cd ${{ github.workspace }}
-          cd src
-          .\build-all.bat
-          cd build
-          msbuild RUN_TESTS.vcxproj /p:Configuration=Release
-
-      # The windows-specific GITHUB_ENV set is not documented, and it's different than unix flavors.  Must use '$env:GITHUB_ENV'
-      # Ref: https://stackoverflow.com/questions/61858388/how-do-i-set-an-enviroment-variable-in-github-action-on-a-windows-server
-      - name: Get Version
-        run: |
-          chcp 65001 #set code page to utf-8
-          $V_VER = Get-Content .\VERSION
-          echo "V_VERSION=$V_VER" >> $env:GITHUB_ENV
-
-      - name: Get Timestamp
-        run : |
-          $V_TSTAMP = Get-Date((Get-Date).toUniversalTime()) -Format "yyyyMMddHHmmss"
-          echo "V_TIMESTAMP=$V_TSTAMP" >> $env:GITHUB_ENV
-
-      - name: Save artifacts
-        uses: actions/upload-artifact@v3
-        if: (github.event_name != 'pull_request') && (github.event_name != 'schedule')
-        with:
-          name: opentdf-client-cpp-win-${{ env.V_VERSION }}-${{ env.V_TIMESTAMP }}
-          path: |
-            dist/*
-
-      - run: echo "🍏 This job's status is %job.status%."
-
-  run-build-mac:
-    runs-on: macos-11
-    needs: run-build-ubuntu
-    steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
-
-      - name: Check out repository code
-        uses: actions/checkout@v3
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-            python-version: 3.11
-
-      - name: Install Conan
-        run: pip3 install conan==${{ env.CONAN_VER }} --force
-
-      - name: Run build
-        run: |
-          cd ${{ github.workspace }}
-          cd src
-          ./build-all.sh
-
-      - name: Get Version
-        run: |
-          VER=$(cat VERSION)
-          echo "V_VERSION=$VER" >> $GITHUB_ENV
-
-      - name: Get Timestamp
-        run : |
-          TSTAMP=$(date +'%Y%m%d%H%M%S')
-          echo "V_TIMESTAMP=$TSTAMP" >> $GITHUB_ENV
-
-      - name: Save artifacts
-        uses: actions/upload-artifact@v3
-        if: (github.event_name != 'pull_request') && (github.event_name != 'schedule')
-        with:
-          name: opentdf-client-cpp-mac-${{ env.V_VERSION }}-${{ env.V_TIMESTAMP }}
-          path: |
-            dist/*
-
-      - run: echo "🍏 This job's status is ${{ job.status }}."
-
-  ci:
-    needs:
-      - run-build-mac
-      - run-build-ubuntu
-      - run-build-windows
-    if: always()
-    runs-on: ubuntu-latest
-    steps:
-      - run: exit 1
-        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+#  run-build-windows:
+#    runs-on: windows-2019
+#    needs: run-build-ubuntu
+#    env:
+#      VBUILDRELEASE: Release
+#      VBUILDDEBUG: Debug
+#      VBUILDMODE: Release
+#    steps:
+#      - run: echo "🎉 The job was automatically triggered by a %github.event_name% event."
+#      - run: echo "🐧 This job is now running on a %runner.os% server hosted by GitHub!"
+#      - run: echo "🔎 The name of your branch is %github.ref% and your repository is %github.repository%."
+#
+#      - name: Check out repository code
+#        uses: actions/checkout@v3
+#      - run: echo "💡 The %github.repository% repository has been cloned to the runner."
+#
+#      - name: Install Conan
+#        run: pip3 install conan==${{ env.CONAN_VER }} --force
+#
+#      - name: Setup MSBuild
+#        uses: microsoft/setup-msbuild@v1
+#
+#      - name: Run build
+#        run: |
+#          cd ${{ github.workspace }}
+#          cd src
+#          .\build-all.bat
+#          cd build
+#          msbuild RUN_TESTS.vcxproj /p:Configuration=Release
+#
+#      # The windows-specific GITHUB_ENV set is not documented, and it's different than unix flavors.  Must use '$env:GITHUB_ENV'
+#      # Ref: https://stackoverflow.com/questions/61858388/how-do-i-set-an-enviroment-variable-in-github-action-on-a-windows-server
+#      - name: Get Version
+#        run: |
+#          chcp 65001 #set code page to utf-8
+#          $V_VER = Get-Content .\VERSION
+#          echo "V_VERSION=$V_VER" >> $env:GITHUB_ENV
+#
+#      - name: Get Timestamp
+#        run : |
+#          $V_TSTAMP = Get-Date((Get-Date).toUniversalTime()) -Format "yyyyMMddHHmmss"
+#          echo "V_TIMESTAMP=$V_TSTAMP" >> $env:GITHUB_ENV
+#
+#      - name: Save artifacts
+#        uses: actions/upload-artifact@v3
+#        if: (github.event_name != 'pull_request') && (github.event_name != 'schedule')
+#        with:
+#          name: opentdf-client-cpp-win-${{ env.V_VERSION }}-${{ env.V_TIMESTAMP }}
+#          path: |
+#            dist/*
+#
+#      - run: echo "🍏 This job's status is %job.status%."
+#
+#  run-build-mac:
+#    runs-on: macos-11
+#    needs: run-build-ubuntu
+#    steps:
+#      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
+#      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
+#      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
+#
+#      - name: Check out repository code
+#        uses: actions/checkout@v3
+#      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
+#
+#      - name: Set up Python
+#        uses: actions/setup-python@v4
+#        with:
+#            python-version: 3.11
+#
+#      - name: Install Conan
+#        run: pip3 install conan==${{ env.CONAN_VER }} --force
+#
+#      - name: Run build
+#        run: |
+#          cd ${{ github.workspace }}
+#          cd src
+#          ./build-all.sh
+#
+#      - name: Get Version
+#        run: |
+#          VER=$(cat VERSION)
+#          echo "V_VERSION=$VER" >> $GITHUB_ENV
+#
+#      - name: Get Timestamp
+#        run : |
+#          TSTAMP=$(date +'%Y%m%d%H%M%S')
+#          echo "V_TIMESTAMP=$TSTAMP" >> $GITHUB_ENV
+#
+#      - name: Save artifacts
+#        uses: actions/upload-artifact@v3
+#        if: (github.event_name != 'pull_request') && (github.event_name != 'schedule')
+#        with:
+#          name: opentdf-client-cpp-mac-${{ env.V_VERSION }}-${{ env.V_TIMESTAMP }}
+#          path: |
+#            dist/*
+#
+#      - run: echo "🍏 This job's status is ${{ job.status }}."
+#
+#  ci:
+#    needs:
+#      - run-build-mac
+#      - run-build-ubuntu
+#      - run-build-windows
+#    if: always()
+#    runs-on: ubuntu-latest
+#    steps:
+#      - run: exit 1
+#        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
